sudo: required
dist: trusty
language: node_js
node_js:
  - "11.10"
cache:
  directories:
    - node_modules
install:
  - npm install -g codecov
  - npm install
script:
  - npm run ci
  - npm run build
  - codecov
notifications:
  email: false
